version: '3.8'
services:
  web:
    build: .
    ports: ["8000:8000"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://django_user:password@db:5432/tododb
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: