apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodoproject-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytodoproject-db
  template:
    metadata:
      labels:
        app: mytodoproject-db
    spec:
      containers:
        - name: mytodoproject-db
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tododb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mytodoproject-db
spec:
  selector:
    app: mytodoproject-db
  ports:
    - port: 5432
      targetPort: 5432