apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodoproject-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytodoproject-web
  template:
    metadata:
      labels:
        app: mytodoproject-web
    spec:
      containers:
        - name: mytodoproject-web
          image: engineer442/mytodoproject-web:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@mytodoproject-db:5432/tododb
          volumeMounts:
            - name: app-storage
              mountPath: /app
          command: [ "bash", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" ]
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mytodoproject-web
spec:
  selector:
    app: mytodoproject-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
