apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodoproject-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytodoproject-web
  template:
    metadata:
      labels:
        app: mytodoproject-web
    spec:
      containers:
        - name: mytodoproject-web
          image: engineer442/mytodoproject-web:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "MyTodoProject.settings"
            - name: DATABASE_URL
              value: "postgres://postgres:$(POSTGRES_PASSWORD)@mytodoproject-db:5432/mydatabase"
          envFrom:
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mytodoproject-web-service
spec:
  selector:
    app: mytodoproject-web
  ports:
    - protocol: TCP
      port: 80  # This is the port that will be exposed inside the cluster
      targetPort: 8000  # This is the port your container is listening on
  type: LoadBalancer  # Change this to NodePort

