apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodoproject-db
  labels:
    app: mytodoproject-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytodoproject-db
  template:
    metadata:
      labels:
        app: mytodoproject-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "tododb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: mytodoproject-db
spec:
  selector:
    app: mytodoproject-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
